# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 177245f21ac470d758415d91b4a4c54b675208a3a1aa74abce4564b3029179f08ff22eae4cb6fef3bcf79482710b57111a6fa6a9d3848b64a299a1ad5ec30e63

test:
  secret_key_base: 04b173f8442edc8c9bcaa137f71f9137dc55fd3c6c5c0d32818a9f8d271c30391c030238e2177785f571cf9e329ef3d188b3633e729cd22d9a3c5cf86337041f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
